### ISSUE TITLE
fix(ldap2rdbm): shibboleth-idp getting issue after migration

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/gluu4#25]
## ERROR

```
2024-11-19 08:08:56,194 - 127.0.0.1 - DEBUG [net.shibboleth.idp.attribute.resolver.spring.dc.rdbms.impl.RDBMSDataConnectorParser:70] - Data Connector 'siteDataConnector': Parsing v2 configuration [DataConnector: null]
2024-11-19 08:08:56,204 - 127.0.0.1 - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:233] - Service 'shibboleth.AttributeRegistryService': Reload for shibboleth.AttributeRegistryService failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'siteDataConnector' defined in null: Could not resolve placeholder 'idp.attribute.resolver.sql.searchFilter' in value "

                %{idp.attribute.resolver.sql.searchFilter}

        "; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'idp.attribute.resolver.sql.searchFilter' in value "

                %{idp.attribute.resolver.sql.searchFilter}

        "
	at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:377)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'siteDataConnector' defined in null: Could not resolve placeholder 'idp.attribute.resolver.sql.searchFilter' in value "

                %{idp.attribute.resolver.sql.searchFilter}

        "; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'idp.attribute.resolver.sql.searchFilter' in value "

                %{idp.attribute.resolver.sql.searchFilter}

        "
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:230)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'idp.attribute.resolver.sql.searchFilter' in value "

                %{idp.attribute.resolver.sql.searchFilter}

        "
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)
2024-11-19 08:08:56,205 - 127.0.0.1 - ERROR [net.shibboleth.idp.profile.impl.ReloadServiceConfiguration:131] - Profile Action ReloadServiceConfiguration: Error reloading service configuration for 'shibboleth.AttributeRegistryService'
2024-11-19 08:08:56,206 - 127.0.0.1 - DEBUG [net.shibboleth.idp.profile.impl.RecordResponseComplete:89] - Profile Action RecordResponseComplete: Record response complete
2024-11-19 08:08:
```

Following doc used to migrate: https://gist.github.com/imShakil/694a0769ebcf679ea63e94e47692103f

**Comment by imShakil** [comment]
Hi, @devrimyatar 

I have tested successfully. It seems issues are resolved.
