### ISSUE TITLE
fix(oxtrust): change cert to idpCert field

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu4#4]
When adding Passport provider using `passport-saml` strategy, the `cert` field should be changed to `idpCert` as stated in https://github.com/GluuFederation/gluu-passport/pull/561. Without the changes, passport app raises the following error:

```
/opt/gluu/node/passport/server/providers.js:111
    providerOptions.idpCert = providerOptions.idpCert.replace(/[\n ]/g, '')
                                                      ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at setupStrategy (/opt/gluu/node/passport/server/providers.js:111:55)
    at forEach (/opt/gluu/node/passport/node_modules/ramda/src/forEach.js:53:5)
    at /opt/gluu/node/passport/node_modules/ramda/src/internal/_checkForMethod.js:25:72
    at Object.f2 [as forEach] (/opt/gluu/node/passport/node_modules/ramda/src/internal/_curry2.js:34:14)
    at Object.setup (/opt/gluu/node/passport/server/providers.js:271:7)
    at reconfigure (/opt/gluu/node/passport/server/app.js:51:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Ref: support ticket 11966

**Comment by shekhar16** [comment]
just for reference 
https://github.com/GluuFederation/gluu-passport/pull/561
