### ISSUE TITLE
test(oxauth): fix AuthorizationChallengeHttpTest#authorizationChallengeFlow_withInvalidUsername_shouldGetError

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/gluu4#49]
## Describe the issue

test(oxauth): fix AuthorizationChallengeHttpTest#authorizationChallengeFlow_withInvalidUsername_shouldGetError

```
PASSED: authorizationChallengeFlow("test_user", "test_user_password", "https://yurem-game-bass.gluu.info/oxauth-rp/home.htm https://client.example.com/cb https://client.example.com/cb1 https://client.example.com/cb2", "https://yurem-game-bass.gluu.info/oxauth-rp/home.htm")
FAILED: authorizationChallengeFlow_withInvalidUsername_shouldGetError("test_user_password", "https://yurem-game-bass.gluu.info/oxauth-rp/home.htm https://client.example.com/cb https://client.example.com/cb1 https://client.example.com/cb2", "https://yurem-game-bass.gluu.info/oxauth-rp/home.htm")
java.lang.AssertionError: expected:<invalid_request> but was:<username_invalid>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at org.gluu.oxauth.ws.rs.AuthorizationChallengeHttpTest.authorizationChallengeFlow_withInvalidUsername_shouldGetError(AuthorizationChallengeHttpTest.java:138)
```

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/gluu4/pull/50
